version: '3.8'

services:
  backend:
    build:
      context: ./backend/cep-finder
      dockerfile: Dockerfile
    container_name: cepfinder-api
    ports:
      - "8080:8080"
    networks:
      - cep-network

  frontend:
    build:
      context: ./frontend/cep-finder
      dockerfile: Dockerfile
    container_name: cepfinder-web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cep-network

networks:
  cep-network:
    driver: bridge